name: Combine requirements.txt

on:
  workflow_dispatch:  # Allows manual trigger (or API trigger)

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone repos and combine requirements.txt
        run: |
          mkdir temp_repos
          > combined_requirements.txt

          # Iterate through the repos from GitHub secret (REPO_LIST)
          echo "$REPO_LIST" | while read repo; do
            if [ -n "$repo" ]; then
              repo_name=$(basename "$repo" .git)
              echo "Cloning $repo..."
              git clone --depth 1 "$repo" "temp_repos/$repo_name"
              if [ -f "temp_repos/$repo_name/requirements.txt" ]; then
                echo "# From $repo_name" >> combined_requirements.txt
                cat "temp_repos/$repo_name/requirements.txt" >> combined_requirements.txt
                echo "" >> combined_requirements.txt
              else
                echo "No requirements.txt in $repo_name"
              fi
            fi
          done

      - name: Show combined requirements
        run: cat combined_requirements.txt

      - name: Save combined requirements.txt
        run: |
          mv combined_requirements.txt requirements.txt
          echo "Combined requirements.txt file saved locally in the repository."
        # No commit or push to remote repository
        env:
          REPO_LIST: ${{ secrets.REPO_LIST }}  # GitHub secret storing the repo URLs
